.intel_syntax noprefix
# Vredrs raw-mode x86_64 native output
# Generated by vredrs build --raw
# No GC, no scheduler, no reflection — zero overhead.

.section .text
.globl _start

_start:
    xor rbp, rbp
    call main
    mov rdi, rax
    mov rax, 60
    syscall

main:
    push rbp
    mov rbp, rsp
    push r12
    sub rsp, 8
    mov rax, 42
    mov rbx, rax
    mov rax, rbx
    add rax, 8
    mov r13, rax
    mov rax, r13
    # print signed int in rax (id 1)
    mov rsi, rsp
    test rax, rax
    jns .Lpin_start_1
    dec rsi
    mov byte ptr [rsi], 45
    neg rax
.Lpin_start_1:
    test rax, rax
    jnz .Lpin_loop_1
    dec rsi
    mov byte ptr [rsi], 48
    jmp .Lpin_write_1
.Lpin_loop_1:
    xor rdx, rdx
    mov rcx, 10
    div rcx
    add dl, 48
    dec rsi
    mov [rsi], dl
    test rax, rax
    jnz .Lpin_loop_1
.Lpin_write_1:
    mov rdx, rsp
    sub rdx, rsi
    mov rax, 1
    mov rdi, 1
    syscall
    mov rax, 1
    mov rdi, 1
    lea rsi, [rip + .str0]
    mov rdx, 1
    syscall
    mov rax, 0
    jmp .Lepi_0
    mov rax, 0
    jmp .Lepi_0
.Lepi_0:
    add rsp, 8
    pop r12
    pop rbp
    ret

.section .rodata
.str0:
    .asciz "\n"
