impl FullLlvmGen {
    fn ty_of_annot(&self, ty: Option<&TypeExpr>) -> Result<Ty> {
        Ok(annot_to_ty(ty))
    }

    fn ty_of_te(&self, ty: &TypeExpr) -> Result<Ty> {
        Ok(type_expr_to_ty(ty))
    }

    fn class_of_annot(&self, ty: Option<&TypeExpr>) -> Option<String> {
        class_of_annot(ty)
    }

    fn intern(&mut self, text: &str) -> String {
        if let Some(n) = self.strs.get(text) {
            return n.clone();
        }
        let name = format!("@.vstr.{}", self.str_n);
        self.str_n += 1;
        self.strs.insert(text.to_string(), name.clone());
        name
    }

    fn intern_str_for(&mut self, text: &str) -> Result<String> {
        let name = self.intern(text);
        let len = text.as_bytes().len() + 1;
        let cptr = self.new_var();
        self.buf.push_str(&format!(
            "  {} = getelementptr inbounds [{} x i8], ptr {}, i64 0, i64 0\n",
            cptr, len, name
        ));
        // Wrap the C string in a vredrs_str so dict/object helpers can read ->len / ->data.
        let sptr = self.new_var();
        self.buf.push_str(&format!(
            "  {} = call %vredrs.str* @vredrs_str_from_cstr(ptr {})\n",
            sptr, cptr
        ));
        Ok(sptr)
    }

    fn emit_header(&mut self) {
        self.buf
            .push_str("; Vredrs LLVM IR — generated by vredrs build (full backend)\n");
        self.buf
            .push_str("target datalayout = \"e-m:e-i64:64-f80:128-n8:16:32:64-S128\"\n");
        self.buf
            .push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");
        self.buf.push_str("%vredrs.value = type { i8, i64 }\n");
        self.buf.push_str("%vredrs.str    = type { i64, i8* }\n");
        self.buf
            .push_str("%vredrs.list   = type { i64, i64, %vredrs.value* }\n");
        self.buf
            .push_str("%vredrs.dict   = type { i64, i64, %vredrs.str**, %vredrs.value* }\n");
        self.buf
            .push_str("%vredrs.tuple  = type { i64, %vredrs.value* }\n");
        self.buf
            .push_str("%vredrs.vtable = type { i64, i8**, %vredrs.vtable*, i8* }\n");
        self.buf
            .push_str("%vredrs.object = type { %vredrs.vtable*, %vredrs.dict*, i64 }\n");
        self.buf
            .push_str("%vredrs.coro   = type { i64, i64, ptr, i64 }\n\n");
        self.buf.push_str("; __STRING_GLOBALS_PLACEHOLDER__\n");
        self.buf
            .push_str("declare i32 @printf(i8* nocapture readonly, ...)\n");
        self.buf.push_str("declare i32 @putchar(i32)\n");
        self.buf
            .push_str("declare i32 @puts(i8* nocapture readonly)\n");
        self.buf.push_str("declare i8* @malloc(i64)\n");
        self.buf.push_str("declare void @free(i8*)\n");
        self.buf.push_str("declare i64 @strtol(i8*, i8**, i32)\n");
        self.buf.push_str("declare double @strtod(i8*, i8**)\n");
        self.buf.push_str("declare i64 @getline(i8**, i64*, i8*)\n");
        self.buf.push_str("declare i32 @fflush(i8*)\n");
        self.buf.push_str("declare i8* @fopen(i8*, i8*)\n");
        self.buf.push_str("declare i32 @fclose(i8*)\n");
        self.buf
            .push_str("declare i64 @fread(i8*, i64, i64, i8*)\n");
        self.buf
            .push_str("declare i64 @fwrite(i8*, i64, i64, i8*)\n");
        self.buf.push_str("declare i32 @fseek(i8*, i64, i32)\n");
        self.buf.push_str("declare i64 @ftell(i8*)\n");
        self.buf.push_str("declare void @exit(i32) noreturn\n");
        self.buf.push_str("@stderr = external global i8*\n");
        // Exception entry points (heap-allocated jmp_buf to survive -O2).
        self.buf
            .push_str("; Exception entry points (heap-allocated jmp_buf)\n");
        self.buf.push_str("declare ptr @vredrs_try_begin()\n");
        self.buf.push_str("declare void @vredrs_try_end(ptr)\n");
        self.buf.push_str("declare void @vredrs_set_jmp_top(ptr)\n");
        self.buf.push_str("declare ptr @vredrs_get_jmp_top()\n");
        self.buf
            .push_str("; setjmp must be called directly in IR (not through a C wrapper)\n");
        self.buf
            .push_str("; so the saved stack frame belongs to THIS function.\n");
        self.buf.push_str("declare i32 @setjmp(ptr) #0\n");
        self.buf
            .push_str("declare void @llvm.eh.sjlj.longjmp(ptr) #1\n\n");
        self.buf
            .push_str("attributes #0 = { returns_twice nounwind }\n");
        self.buf
            .push_str("attributes #1 = { noreturn nounwind }\n\n");
        let decls = [
            "%vredrs.str* @vredrs_str_new(ptr, i64)",
            "%vredrs.str* @vredrs_str_from_cstr(ptr)",
            "%vredrs.str* @vredrs_str_concat(%vredrs.str*, %vredrs.str*)",
            "i64 @vredrs_str_len(%vredrs.str*)",
            "i8* @vredrs_str_data(%vredrs.str*)",
            "i64 @vredrs_str_eq(%vredrs.str*, %vredrs.str*)",
            "%vredrs.str* @vredrs_str_from_i64(i64)",
            "%vredrs.str* @vredrs_str_from_f64(double)",
            "%vredrs.str* @vredrs_str_from_bool(i64)",
            "%vredrs.str* @vredrs_str_of_i64(i64)",
            "%vredrs.str* @vredrs_str_of_f64(double)",
            "%vredrs.str* @vredrs_str_of_bool(i64)",
            "%vredrs.str* @vredrs_str_of_str(%vredrs.str*)",
            "%vredrs.str* @vredrs_str_of_ptr(i8*)",
            "%vredrs.list* @vredrs_list_new()",
            "i64 @vredrs_list_len(%vredrs.list*)",
            "void @vredrs_list_push(%vredrs.list*, %vredrs.value)",
            "%vredrs.value @vredrs_list_get(%vredrs.list*, i64)",
            "void @vredrs_list_set(%vredrs.list*, i64, %vredrs.value)",
            "%vredrs.value @vredrs_list_pop(%vredrs.list*)",
            "i64 @vredrs_list_contains(%vredrs.list*, %vredrs.value)",
            "%vredrs.list* @vredrs_list_slice(%vredrs.list*, i64, i64)",
            "%vredrs.list* @vredrs_list_slice_full(%vredrs.list*, i64, i64, i64)",
            "%vredrs.str* @vredrs_str_slice_full(%vredrs.str*, i64, i64, i64)",
            "%vredrs.dict* @vredrs_dict_new()",
            "i64 @vredrs_dict_len(%vredrs.dict*)",
            "void @vredrs_dict_set(%vredrs.dict*, %vredrs.str*, %vredrs.value)",
            "%vredrs.value @vredrs_dict_get(%vredrs.dict*, %vredrs.str*, %vredrs.value)",
            "i64 @vredrs_dict_has(%vredrs.dict*, %vredrs.str*)",
            "void @vredrs_dict_del(%vredrs.dict*, %vredrs.str*)",
            "%vredrs.list* @vredrs_dict_keys(%vredrs.dict*)",
            "%vredrs.list* @vredrs_dict_values(%vredrs.dict*)",
            "%vredrs.tuple* @vredrs_tuple_new(i64)",
            "void @vredrs_tuple_set_init(%vredrs.tuple*, i64, %vredrs.value)",
            "%vredrs.value @vredrs_tuple_get(%vredrs.tuple*, i64)",
            "i64 @vredrs_tuple_len(%vredrs.tuple*)",
            "i64 @vredrs_set_has(%vredrs.dict*, %vredrs.str*)",
            "void @vredrs_set_add(%vredrs.dict*, %vredrs.str*)",
            "i64 @vredrs_set_len(%vredrs.dict*)",
            "%vredrs.object* @vredrs_object_new(%vredrs.vtable*)",
            "void @vredrs_object_set_field(%vredrs.object*, %vredrs.str*, %vredrs.value)",
            "%vredrs.value @vredrs_object_get_field(%vredrs.object*, %vredrs.str*, %vredrs.value)",
            "i64 @vredrs_object_has_field(%vredrs.object*, %vredrs.str*)",
            "void @vredrs_object_del_field(%vredrs.object*, %vredrs.str*)",
            "ptr @vredrs_object_get_method(%vredrs.object*, i64)",
            "void @vredrs_inc_ref(%vredrs.object*)",
            "void @vredrs_dec_ref(%vredrs.object*)",
            "%vredrs.vtable* @vredrs_object_vtable(%vredrs.object*)",
            "%vredrs.vtable* @vredrs_vtable_parent(%vredrs.vtable*)",
            "%vredrs.coro* @vredrs_coro_alloc()",
            "i64 @vredrs_coro_result(%vredrs.coro*)",
            "void @vredrs_coro_store_result(%vredrs.coro*, i64)",
            "void @vredrs_coro_set_state(%vredrs.coro*, i64)",
            "i64 @vredrs_coro_state(%vredrs.coro*)",
            "%vredrs.list* @vredrs_coro_get_list(%vredrs.coro*)",
            "void @vredrs_coro_set_list(%vredrs.coro*, %vredrs.list*)",
            "i64 @vredrs_coro_get_index(%vredrs.coro*)",
            "void @vredrs_coro_set_index(%vredrs.coro*, i64)",
            "i64 @vredrs_get_exception_i64()",
            "%vredrs.str* @vredrs_get_exception_str()",
            "void @vredrs_clear_exception()",
            "void @vredrs_throw_i64(i64)",
            "void @vredrs_throw_str(%vredrs.str*)",
            "i64 @vredrs_len_str(%vredrs.str*)",
            "i64 @vredrs_len_list(%vredrs.list*)",
            "i64 @vredrs_len_dict(%vredrs.dict*)",
            "i64 @vredrs_len_tuple(%vredrs.tuple*)",
            "i64 @vredrs_int_of_str(%vredrs.str*)",
            "i64 @vredrs_int_of_f64(double)",
            "double @vredrs_float_of_str(%vredrs.str*)",
            "double @vredrs_float_of_i64(i64)",
            "i64 @vredrs_bool_of_str(%vredrs.str*)",
            "%vredrs.list* @vredrs_range(i64, i64)",
            "%vredrs.list* @vredrs_range1(i64)",
            "%vredrs.list* @vredrs_enumerate(%vredrs.list*)",
            "%vredrs.list* @vredrs_zip(%vredrs.list*, %vredrs.list*)",
            "i64 @vredrs_sum(%vredrs.list*)",
            "i64 @vredrs_min(%vredrs.list*)",
            "i64 @vredrs_max(%vredrs.list*)",
            "%vredrs.list* @vredrs_sorted(%vredrs.list*)",
            "%vredrs.list* @vredrs_reversed(%vredrs.list*)",
            "i64 @vredrs_print_str(%vredrs.str*)",
            "i64 @vredrs_print_i64(i64)",
            "i64 @vredrs_print_f64(double)",
            "i64 @vredrs_print_bool(i64)",
            "i64 @vredrs_print_cstr(i8*)",
            "i64 @vredrs_println()",
            "i64 @vredrs_print_space()",
            "%vredrs.str* @vredrs_input(%vredrs.str*)",
            "i64 @vredrs_open(%vredrs.str*, %vredrs.str*)",
            "void @vredrs_close(i64)",
            "%vredrs.str* @vredrs_read(i64, i64)",
            "i64 @vredrs_write(i64, %vredrs.str*)",
            "%vredrs.str* @vredrs_read_file(%vredrs.str*)",
            "i64 @vredrs_write_file(%vredrs.str*, %vredrs.str*)",
            "i64 @vredrs_file_exists(%vredrs.str*)",
            "void @vredrs_exit(i64)",
            "%vredrs.value @vredrs_value_make_i64(i64)",
            "%vredrs.value @vredrs_value_make_f64(double)",
            "%vredrs.value @vredrs_value_make_bool(i64)",
            "%vredrs.value @vredrs_value_make_str(%vredrs.str*)",
            "%vredrs.value @vredrs_value_make_list(%vredrs.list*)",
            "%vredrs.value @vredrs_value_make_dict(%vredrs.dict*)",
            "%vredrs.value @vredrs_value_make_tuple(%vredrs.tuple*)",
            "%vredrs.value @vredrs_value_make_obj(%vredrs.object*)",
            "%vredrs.value @vredrs_value_make_coro(%vredrs.coro*)",
            "%vredrs.value @vredrs_value_nil()",
            "i64 @vredrs_value_tag(%vredrs.value)",
            "i64 @vredrs_value_get_i64(%vredrs.value)",
            "double @vredrs_value_get_f64(%vredrs.value)",
            "%vredrs.str* @vredrs_value_get_str(%vredrs.value)",
            "%vredrs.list* @vredrs_value_get_list(%vredrs.value)",
            "%vredrs.dict* @vredrs_value_get_dict(%vredrs.value)",
            "%vredrs.tuple* @vredrs_value_get_tuple(%vredrs.value)",
            "%vredrs.object* @vredrs_value_get_obj(%vredrs.value)",
            "%vredrs.str* @vredrs_value_to_str(%vredrs.value)",
            "void @vredrs_value_print(%vredrs.value)",
            "i64 @vredrs_value_truthy(%vredrs.value)",
            "i64 @vredrs_value_eq(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_value_ne(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_value_lt(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_value_gt(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_value_le(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_value_ge(%vredrs.value, %vredrs.value)",
            "%vredrs.value @vredrs_value_add(%vredrs.value, %vredrs.value)",
            "%vredrs.value @vredrs_value_sub(%vredrs.value, %vredrs.value)",
            "%vredrs.value @vredrs_value_mul(%vredrs.value, %vredrs.value)",
            "%vredrs.value @vredrs_value_div(%vredrs.value, %vredrs.value)",
            "%vredrs.value @vredrs_value_mod(%vredrs.value, %vredrs.value)",
            "i64 @vredrs_print_value(%vredrs.value)",
            "%vredrs.value @vredrs_value_index(%vredrs.value, %vredrs.value)",
            "ptr @vredrs_value_class_name(%vredrs.value)",
            // Math function used by the `**` (Power) operator.
            "double @pow(double, double)",
            // String / list repetition used by the `repeated` operator.
            "%vredrs.str* @vredrs_str_repeat(%vredrs.str*, i64)",
            "%vredrs.list* @vredrs_list_repeat(%vredrs.list*, i64)",
        ];
        for d in &decls {
            self.buf.push_str(&format!("declare {}\n", d));
        }
        self.buf.push('\n');
        self.buf.push_str(
            "@.fmt.i64 = private unnamed_addr constant [5 x i8] c\"%lld\\00\", align 1\n",
        );
        self.buf
            .push_str("@.fmt.f64 = private unnamed_addr constant [3 x i8] c\"%g\\00\", align 1\n");
        self.buf
            .push_str("@.fmt.str = private unnamed_addr constant [3 x i8] c\"%s\\00\", align 1\n");
        self.buf.push_str(
            "@.lit.true  = private unnamed_addr constant [5 x i8] c\"true\\00\", align 1\n",
        );
        self.buf.push_str(
            "@.lit.false = private unnamed_addr constant [6 x i8] c\"false\\00\", align 1\n\n",
        );
    }

    fn emit_string_globals(&mut self) {
        if self.strs.is_empty() {
            return;
        }
        self.buf.push_str("; --- String literals ---\n");
        let mut entries: Vec<(&String, &String)> = self.strs.iter().collect();
        entries.sort_by_key(|(_, n)| *n);
        for (text, name) in entries {
            let bytes = text.as_bytes();
            let len = bytes.len() + 1;
            let mut esc = String::new();
            for &b in bytes {
                match b {
                    b'\n' => esc.push_str("\\0A"),
                    b'\r' => esc.push_str("\\0D"),
                    b'\t' => esc.push_str("\\09"),
                    b'\\' => esc.push_str("\\5C"),
                    b'"' => esc.push_str("\\22"),
                    0x20..=0x7e => esc.push(b as char),
                    b => esc.push_str(&format!("\\{:02X}", b)),
                }
            }
            esc.push_str("\\00");
            self.buf.push_str(&format!(
                "{} = private unnamed_addr constant [{} x i8] c\"{}\", align 1\n",
                name, len, esc
            ));
        }
        self.buf.push('\n');
    }

    fn emit_class_vtables(&mut self, local_classes: &std::collections::HashSet<String>) {
        if self.classes.is_empty() {
            return;
        }
        self.buf.push_str("; --- Class vtables ---\n");
        let mut names: Vec<String> = self.classes.keys().cloned().collect();
        names.sort();
        for name in &names {
            // Only emit vtables for classes defined in THIS module. Classes
            // from imported modules are referenced as external symbols.
            if !local_classes.contains(name) {
                continue;
            }
            let c = self.classes[name].clone();
            let methods = c.methods.clone();
            let n = methods.len();
            let arr_name = format!("@{}.vmethods", self.safe(name));
            let vt_name = format!("@{}.vtable", self.safe(name));
            let parent_name = match &c.parent {
                Some(p) => format!("@{}.vtable", self.safe(p)),
                None => "null".to_string(),
            };
            let class_name_str = self.intern(name);
            let entries: Vec<String> = methods
                .iter()
                .map(|m| format!("i8* bitcast (ptr @{} to i8*)", m.llvm_name))
                .collect();
            let class_name_len = name.len() + 1;
            if n == 0 {
                self.buf.push_str(&format!(
                    "{} = private global [1 x i8*] [i8* null]\n",
                    arr_name
                ));
                self.buf.push_str(&format!(
                    "{} = global %vredrs.vtable {{ i64 0, ptr getelementptr inbounds ([1 x i8*], ptr {}, i64 0, i64 0), ptr {}, ptr getelementptr inbounds ([{} x i8], ptr {}, i64 0, i64 0) }}\n",
                    vt_name, arr_name, parent_name, class_name_len, class_name_str));
            } else {
                self.buf.push_str(&format!(
                    "{} = private global [{} x i8*] [{}]\n",
                    arr_name,
                    n,
                    entries.join(", ")
                ));
                self.buf.push_str(&format!(
                    "{} = global %vredrs.vtable {{ i64 {}, ptr getelementptr inbounds ([{} x i8*], ptr {}, i64 0, i64 0), ptr {}, ptr getelementptr inbounds ([{} x i8], ptr {}, i64 0, i64 0) }}\n",
                    vt_name, n, n, arr_name, parent_name, class_name_len, class_name_str));
            }
        }
        self.buf.push('\n');
    }

    /* -- function & method bodies -- */
    fn gen_function(&mut self, f: &FnDef) -> Result<()> {
        // If this function contains yield, compile it as a generator coroutine.
        if self.body_has_yield(&f.body) && !f.is_async {
            return self.gen_generator_function(f);
        }
        let sig = self.functions.get(&f.name.name).cloned().ok_or_else(|| {
            CompilerError::codegen_error(format!("missing sig for fn '{}'", f.name.name))
        })?;
        let mut params = String::new();
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                params.push_str(", ");
            }
            params.push_str(&format!("{} %{}", sig.params[i].ir(), p.name.name));
        }
        self.buf.push_str(&format!(
            "define {} @{}({}) {{\nentry:\n",
            sig.ret.ir(),
            self.safe(&f.name.name),
            params
        ));
        let mut vars: HashMap<String, LocalSlot> = HashMap::new();
        for (i, p) in f.params.iter().enumerate() {
            let ty = sig.params[i].clone();
            let ptr = self.new_local(&p.name.name);
            self.buf
                .push_str(&format!("  {} = alloca {}, align 8\n", ptr, ty.ir()));
            self.buf.push_str(&format!(
                "  store {} %{}, {}* {}, align 8\n",
                ty.ir(),
                p.name.name,
                ty.ir(),
                ptr
            ));
            vars.insert(
                p.name.name.clone(),
                LocalSlot {
                    ty: ty.clone(),
                    ptr,
                    class: self.class_of_annot(p.type_annotation.as_ref()),
                    async_fn: None,
                    closure_sig: None,
                },
            );
        }
        let terminated = self.gen_block(&f.body, &mut vars, &sig.ret)?;
        if !terminated {
            self.emit_default_ret(&sig.ret)?;
        }
        self.buf.push_str("}\n\n");
        Ok(())
    }

    /// Compile a generator function (one that contains `yield`).
    ///
    /// Eager semantics: the first poll runs the entire body, collecting all
    /// yielded values into a list stored in the coro's impl field. The first
    /// yielded value is returned. Subsequent polls read the next value from
    /// the list. When the list is exhausted, the coro is marked done.
    ///
    /// This means the generator body runs to completion on the first resume()
    /// call, and side effects in the body happen eagerly.
    fn gen_generator_function(&mut self, f: &FnDef) -> Result<()> {
        let ctor = self.safe(&f.name.name);
        let poll = format!("{}_poll", ctor);
        // Constructor: allocate coro + an empty list, return coro.
        self.buf
            .push_str(&format!("; generator {} constructor\n", f.name.name));
        self.buf
            .push_str(&format!("define %vredrs.coro* @{}() {{\nentry:\n", ctor));
        self.buf
            .push_str("  %coro = call %vredrs.coro* @vredrs_coro_alloc()\n");
        self.buf
            .push_str("  %list = call %vredrs.list* @vredrs_list_new()\n");
        self.buf.push_str(
            "  call void @vredrs_coro_set_list(%vredrs.coro* %coro, %vredrs.list* %list)\n",
        );
        self.buf
            .push_str("  call void @vredrs_coro_set_index(%vredrs.coro* %coro, i64 0)\n");
        self.buf.push_str("  ret %vredrs.coro* %coro\n}\n\n");
        // Poll function: on first call (state==0), run the body to collect
        // yields into the list. Then read the next value from the list.
        self.buf
            .push_str(&format!("; generator {} poll (eager)\n", f.name.name));
        self.buf.push_str(&format!(
            "define i1 @{}(%vredrs.coro* %coro) {{\nentry:\n",
            poll
        ));
        // Check if body has been run (state == 0 means not run yet).
        self.buf.push_str(
            "  %state.slot = getelementptr inbounds %vredrs.coro, ptr %coro, i32 0, i32 0\n",
        );
        self.buf
            .push_str("  %state = load i64, i64* %state.slot, align 8\n");
        self.buf.push_str("  %not_run = icmp eq i64 %state, 0\n");
        let run_body_lbl = self.new_lbl();
        let read_list_lbl = self.new_lbl();
        self.buf.push_str(&format!(
            "  br i1 %not_run, label %L{}, label %L{}\n",
            run_body_lbl, read_list_lbl
        ));
        // Run body: yield pushes to the list.
        self.buf.push_str(&format!("L{}:\n", run_body_lbl));
        let mut vars: HashMap<String, LocalSlot> = HashMap::new();
        vars.insert(
            "__coro".to_string(),
            LocalSlot {
                ty: Ty::Coro,
                ptr: "%coro.addr.synthetic".to_string(),
                class: None,
                async_fn: Some(f.name.name.clone()),
                    closure_sig: None,
            },
        );
        // Mark state as 1 (running) so yield knows to push to the list.
        self.buf
            .push_str("  call void @vredrs_coro_set_state(%vredrs.coro* %coro, i64 1)\n");
        let _ = self.gen_async_block(&f.body, &mut vars)?;
        // Body done. Set state to 2 (done collecting).
        self.buf
            .push_str("  call void @vredrs_coro_set_state(%vredrs.coro* %coro, i64 2)\n");
        self.buf
            .push_str(&format!("  br label %L{}\n", read_list_lbl));
        // Read next value from the list.
        self.buf.push_str(&format!("L{}:\n", read_list_lbl));
        self.buf
            .push_str("  %list = call %vredrs.list* @vredrs_coro_get_list(%vredrs.coro* %coro)\n");
        self.buf
            .push_str("  %idx = call i64 @vredrs_coro_get_index(%vredrs.coro* %coro)\n");
        self.buf
            .push_str("  %len = call i64 @vredrs_list_len(%vredrs.list* %list)\n");
        self.buf.push_str("  %has_more = icmp slt i64 %idx, %len\n");
        let has_more_lbl = self.new_lbl();
        let done_lbl = self.new_lbl();
        self.buf.push_str(&format!(
            "  br i1 %has_more, label %L{}, label %L{}\n",
            has_more_lbl, done_lbl
        ));
        self.buf.push_str(&format!("L{}:\n", has_more_lbl));
        self.buf.push_str(
            "  %val = call %vredrs.value @vredrs_list_get(%vredrs.list* %list, i64 %idx)\n",
        );
        self.buf.push_str("  %next_idx = add i64 %idx, 1\n");
        self.buf
            .push_str("  call void @vredrs_coro_set_index(%vredrs.coro* %coro, i64 %next_idx)\n");
        // Store the value as the coro result (as i64 for compatibility).
        self.buf
            .push_str("  %val_i64 = call i64 @vredrs_value_get_i64(%vredrs.value %val)\n");
        self.buf
            .push_str("  call void @vredrs_coro_store_result(%vredrs.coro* %coro, i64 %val_i64)\n");
        self.buf.push_str("  ret i1 false\n");
        self.buf.push_str(&format!("L{}:\n", done_lbl));
        self.buf
            .push_str("  call void @vredrs_coro_set_state(%vredrs.coro* %coro, i64 3)\n");
        self.buf.push_str("  ret i1 true\n");
        self.buf.push_str("}\n\n");
        Ok(())
    }

    fn gen_method_function(&mut self, c: &ClassInfo, m: &MethodInfo) -> Result<()> {
        let mut params = vec!["%vredrs.object* %self".to_string()];
        for (i, p) in m.fn_def.params.iter().enumerate() {
            params.push(format!("{} %{}", m.sig.params[i].ir(), p.name.name));
        }
        self.buf
            .push_str(&format!("; method {}.{}\n", c.name, m.name));
        self.buf.push_str(&format!(
            "define {} @{}({}) {{\nentry:\n",
            m.sig.ret.ir(),
            m.llvm_name,
            params.join(", ")
        ));
        let mut vars: HashMap<String, LocalSlot> = HashMap::new();
        let self_ptr = self.new_local("self");
        self.buf.push_str(&format!(
            "  {} = alloca %vredrs.object*, align 8\n",
            self_ptr
        ));
        self.buf.push_str(&format!(
            "  store %vredrs.object* %self, %vredrs.object** {}, align 8\n",
            self_ptr
        ));
        let self_ptr_clone = self_ptr.clone();
        vars.insert(
            "self".to_string(),
            LocalSlot {
                ty: Ty::Obj,
                ptr: self_ptr_clone,
                class: Some(c.name.clone()),
                async_fn: None,
                    closure_sig: None,
            },
        );
        if let Some(pn) = &c.parent {
            // super.method() — the IR uses the same self pointer but resolves
            // methods through the parent vtable. We store the parent class
            // name in a synthetic local so super-call codegen can find it.
            vars.insert(
                "__super_class".to_string(),
                LocalSlot {
                    ty: Ty::Obj,
                    ptr: self_ptr,
                    class: Some(pn.clone()),
                    async_fn: None,
                    closure_sig: None,
                },
            );
        }
        for (i, p) in m.fn_def.params.iter().enumerate() {
            let ty = m.sig.params[i].clone();
            let ptr = self.new_local(&p.name.name);
            self.buf
                .push_str(&format!("  {} = alloca {}, align 8\n", ptr, ty.ir()));
            self.buf.push_str(&format!(
                "  store {} %{}, {}* {}, align 8\n",
                ty.ir(),
                p.name.name,
                ty.ir(),
                ptr
            ));
            vars.insert(
                p.name.name.clone(),
                LocalSlot {
                    ty: ty.clone(),
                    ptr,
                    class: self.class_of_annot(p.type_annotation.as_ref()),
                    async_fn: None,
                    closure_sig: None,
                },
            );
        }
        let terminated = self.gen_block(&m.fn_def.body, &mut vars, &m.sig.ret)?;
        if !terminated {
            self.emit_default_ret(&m.sig.ret)?;
        }
        self.buf.push_str("}\n\n");
        Ok(())
    }


}
